### ISSUE TITLE
PySimpleGUI.finalize reference has no effect

### ISSUE THREAD

**Issue by PySimpleGUI** [tsontario/minerva#15]
I noticed this code while reading through your user interface code:

```python
    window = sg.Window("Minerva Search Engine", layout)
    window.Finalize
```

The finalize statement needs to be a call, or you can set the finalize parameter when creating the window.

Use either:

```python
    window = sg.Window("Minerva Search Engine", layout, finalize=True)
```

or:

```python
    window = sg.Window("Minerva Search Engine", layout)
    window.Finalize()
```

However I don't see any reason it needs finalizing regardless so it can be removed.  You only need to finalize if you are trying to manipulate the window prior to calling `window.read()`.  I don't see any attempts to access the window prior to your `read()` so it's safe to remove.

**Comment by aethelind** [comment]
Good catch, I'll remove it. I'm not sure why I added that line to begin with. Thanks!
