### ISSUE TITLE
Wildcard token issue

### ISSUE THREAD

**Issue by aethelind** [tsontario/minerva#19]
I think something's funky with the wildcard part of the boolean module. I was testing queries for the UI and it gave me errors for queries like "linear AND algebra". Also tried it from parser.py to see if it was the UI's fault, but same thing there. 

eg. for query "linear AND algebra"
![image](https://user-images.githubusercontent.com/42299845/74476801-201c7780-4e78-11ea-8232-5f63a8ef0403.png)

From a quick look it seems like the wildcard method is adding a few too many ' OR ' tokens or something. Vanilla boolean queries work fine when I comment out the wildcard stuff. 
@tsontario Maybe you can take a look when you have time? :)

**Comment by timothysmith0609** [comment]
Hmm I will check I thought I had accounted for that.

**Comment by aethelind** [comment]
Fixed by #21
